# Generated by Django 2.1.7 on 2019-05-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sproject_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
    ]
