# Generated by Django 2.1.7 on 2019-05-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproject_manager', '0002_auto_20190514_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('PND', 'PENDING'), ('CLS', 'CLOSED')], default='ACT', max_length=3),
        ),
    ]
