# Generated by Django 2.2.1 on 2019-05-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproject_manager', '0006_auto_20190518_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
