# Generated by Django 2.2.1 on 2019-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproject_manager', '0008_auto_20190518_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
